version: '3.9'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    command: ["redis-server", "--loadmodule", "/opt/redis-stack/lib/redisbloom.so", "--requirepass", "admin"]
    volumes:
      - ./redis-data:/data
    environment:
      - REDIS_PASSWORD=admin
    networks:
      - rate-limiter





networks:
  rate-limiter:
    driver: bridge
